# Generated by Django 4.2.5 on 2024-01-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_categoria_options_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(default='api', max_length=255, unique=True),
        ),
    ]
