# Generated by Django 4.2.5 on 2024-01-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_categoria_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(default='cursos-e-palestras', max_length=255, unique=True),
        ),
    ]
